from src.modules.entities.items.BlowBomb import BlowBomb
from src.modules.entities.items.Door import Door
from src.modules.entities.items.FirePlace import FirePlace
from src.modules.entities.items.PickBomb import PickBomb
from src.modules.entities.items.PickKey import PickKey
from src.modules.entities.items.PickMoney import PickMoney
from src.modules.entities.items.Poop import Poop
from src.modules.entities.items.Rock import Rock
from src.modules.entities.items.Spikes import Spikes
from src.modules.entities.items.Web import Web
